name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        only-new-issues: false
        skip-go-installation: true
        skip-pkg-cache: false
        skip-build-cache: false
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -race -coverprofile /dev/null
